name: CodeClimate

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  nodejs:
    name: CodeClimate Upload
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.5
      - name: npm install
        run: npm install
        working-directory: ./
      - name: npm build
        run: npm build
        working-directory: ./
      - name: npm test
        run: npm test
        working-directory: ./
      - name: npm coverage
        run: npm test -- --coverage
        working-directory: ./
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ffed1511681f6befb382901ee070c5465ab4585684371ac7403431583eee75d7
